name: monorepo統合監視（毎日9AM JST）

on:
  schedule:
    # 毎日9:00 JST（0:00 UTC）
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  health-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js 20セットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 依存関係をインストール
        run: |
          cd packages/shared
          npm install

      - name: 全サイトの健全性チェック
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          node packages/shared/scripts/monitor-all-sites.cjs

      # Discord通知は無効化（GitHub Actionsの結果はメールで受信）
